### ISSUE TITLE
r4p0 is out

### ISSUE THREAD

**Issue by WebReflection** [linux-sunxi/sunxi-mali-proprietary#3]
any chance we can have this in ?
http://malideveloper.arm.com/develop-for-mali/drivers/open-source-mali-gpus-linux-kernel-device-drivers/

looks like someone is still improving/working on this GPU ;-)

Thanks

**Comment by libv** [comment]
-ENOR4P0BLOBS

**Comment by libv** [comment]
But thanks for the heads up though.

**Comment by WebReflection** [comment]
np … not sure I got your first answer though … pretty sure that made sense to you

**Comment by libv** [comment]
That's a link to kernel source. You filed a bug against the repository which holds the userspace binary blobs. There are no binary blobs yet to match this kernel driver.

**Comment by WebReflection** [comment]
yeah, apologies for bothering, actually I didn't want to file a bug at all but this was the quickest way for the heads up ;-)

take care
